repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/commit-check/commit-check
  rev: v0.10.2
  hooks:
  - id: check-message
  - id: check-branch
  - id: check-author-name
  - id: check-author-email
