name: Commit Check

on:
  push:
  pull_request:
    branches: ['main']

jobs:
  commit-check:
    runs-on: ubuntu-latest
    permissions:  # use permissions because of use pr-comments
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}  # checkout PR branch
          fetch-depth: 0  # required for merge-base check
      - uses: commit-check/commit-check-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # use GITHUB_TOKEN because of use pr-comments
        with:
          message: true
          branch: true
          author-name: false
          author-email: false
          merge-base: false
          job-summary: true
          pr-comments: ${{ github.event_name == 'pull_request' }}
